apiVersion: apps/v1
kind: Deployment
metadata:
  name: playhive-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playhive-app
  template:
    metadata:
      labels:
        app: playhive-app
    spec:
      containers:
        - name: playhive-app
          image: tejubagalad/playhive-app:latest
          ports:
            - containerPort: 80   # assuming your app listens on 80
---
apiVersion: v1
kind: Service
metadata:
  name: playhive-app-service
spec:
  type: NodePort
  selector:
    app: playhive-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # optional: nodePort: 30080  # you can set a fixed NodePort if you want

